import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <header className="bg-white border-b border-border py-4 px-6 sticky top-0 z-10">
          <div className="max-w-5xl mx-auto flex justify-between items-center">
            <h1 className="text-2xl font-bold text-primary tracking-tight">UniZoy Jobs</h1>
            <nav className="space-x-4">
              <a href="/" className="text-secondary hover:text-primary transition-colors font-medium">Browse Jobs</a>
              <a href="/admin" className="bg-primary text-primary-foreground px-4 py-2 rounded-lg hover:opacity-90 transition-opacity font-medium">Post a Job</a>
            </nav>
          </div>
        </header>
        <main className="flex-grow max-w-5xl mx-auto w-full p-6">
          {children}
        </main>
        <footer className="bg-white border-t border-border py-8 px-6 mt-12">
          <div className="max-w-5xl mx-auto text-center text-secondary">
            <p>© 2026 UniZoy Job Board. Built for Excellence.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
